version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.app.entrypoints=http
      - traefik.http.services.app.loadbalancer.server.port=8080
      - traefik.http.routers.app.rule=Host(`web.shadyseko.dedyn.io`)
    networks:
      - traefik

networks:
  traefik:
    external: true

